apiVersion: v1
kind: Service
metadata:
  name: local
spec:
  selector:
    app: local
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5173
    targetPort: 5173
    nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-depl
  labels:
    app: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local
  template:
    metadata:
      labels:
        app: local
    spec:
      containers:
      - name: toctx
        image: todocontext:1.0
        ports:
          - containerPort: 5173