apiVersion: v1
kind: Service
# metadata of the service
metadata:
  name: nginx-service
# spec of the service
spec:
  # selector of the service(same as the label of the deployment)
  selector:
    app: nginx
  # ports of the service 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80